### ISSUE TITLE
Get back old posts from newsmanager backup folder "posts" in /backup

### ISSUE THREAD

**Issue by steps56** [cnb/News_Manager-getsimplecms#288]
Hello,
just set up a clone of a website in use by newest GetSimple cms.
I could manage to get all stuff transmitted, but just see no way to import the old Newsmanger posts from the actual site (stored in /backups/posts as I assume) in use, to its new setup clone.
Is there any way to get those posts imported?
Thanks in advance for any hints and help about it.
Bye for now.
Steps

**Comment by cnb** [comment]
Posts are stored in `data/posts`.
Just copy all *.xml files from that folder to your new site's `data/posts`.
~~You may have to delete the index file (`data/other/news_manager/posts.xml`) to see your posts in the NM Admin page (or just create and delete some post to force updating the index file).~~

Edit: I didn't remember I already fixed this in #210 - you just have to visit the NM Admin page so that the index file is re-generated.

**Comment by steps56** [comment]
Thanks a lot.
I got all stuff transferred.
New old Website ist now final and working nice.
(Old Website now used as a Testsite)
